<?php

namespace WaterProof\PinBoardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PinRepository extends EntityRepository
{
}
